#!/bin/bash

BASE="/dev/shm/home.$(whoami)"
mkdir -p "${BASE}"

linkDirs=( .config/minecraft .config/thumbnails )
for (( i = 0; i < ${#linkDirs[@]}; ++i )); do
	mkdir -p "${BASE}/${linkDirs[$i]}"
	if [[ ! -h "${HOME}/${linkDirs[$i]}" ]] ||
		[[ "$(readlink "${HOME}/${linkDirs[$i]}")" != "${BASE}/${linkDirs[$i]}" ]]; then
		rm -f -r "${HOME}/${linkDirs[$i]}"
		ln -s "${BASE}/${linkDirs[$i]}" "${HOME}/${linkDirs[$i]}"
	fi
done

if [[ $(tty) == "/dev/tty1" ]]; then
	setfont /usr/share/kbd/consolefonts/ter-u12n.psf.gz
fi

